---
sudo: false
language: ruby
cache: bundler
notifications:
  email: false
before_install: gem install bundler --version '~> 2.1'
script: 'bundle exec rake spec'
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
